services:
  postgres:
    image: postgres:15-alpine
    container_name: cloud-storage-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_storage
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloud-storage-network

volumes:
  postgres_data:
    driver: local

networks:
  cloud-storage-network:
    driver: bridge
